### ISSUE TITLE
instrument_sqlalchemy not working on Python 2.7

### ISSUE THREAD

**Issue by HanimHank** [scoutapp/scout_apm_python#105]
I'm trying to instrument Flask SQLAlchemy queries as follows:

```
from flask import Flask, session
from flask_sqlalchemy import SQLAlchemy
from scout_apm.flask import ScoutApm
from scout_apm.flask.sqlalchemy import instrument_sqlalchemy
app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
ScoutApm(app)
instrument_sqlalchemy(db)
```

When I get the following error:

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "C:\Users\Kamran Khan\python\wrestling\app\__init__.py", line 6, in <module>
    from scout_apm.flask.sqlalchemy import instrument_sqlalchemy
  File "C:\Users\Kamran Khan\.virtualenvs\wrestling\lib\site-packages\scout_apm\flask\sqlalchemy.py", line 5, in <module>
    from sqlalchemy import event
ImportError: cannot import name event
```

Could this have to do with Python 2.7? (2.7.15)

Thank you.

**Comment by cschneid** [comment]
Hi @HanimHank - we don't support Python 2.7 right now (Follow #45 for updates).
